// Package stone ...
package stone

// Texture constants
const (
	// stone
	BloodMarble   = "Blood_Marble"
	BlueAgate     = "Blue_Agate"
	BrownAgate    = "Brown_Agate"
	Jade          = "Jade"
	PinkAlabaster = "PinkAlabaster"
	PinkGranite   = "Pink_Granite"
	RedMarble     = "Red_Marble"
	SapphireAgate = "Sapphire_Agate"
	WhiteMarble   = "White_Marble"
	Stone1        = "T_Stone1"
	Stone2        = "T_Stone2"
	Stone3        = "T_Stone3"
	Stone4        = "T_Stone4"
	Stone5        = "T_Stone5"
	Stone6        = "T_Stone6"
	Stone7        = "T_Stone7"
	Stone8        = "T_Stone8"
	Stone9        = "T_Stone9"
	Stone10       = "T_Stone10"
	Stone11       = "T_Stone11"
	Stone12       = "T_Stone12"
	Stone13       = "T_Stone13"
	Stone14       = "T_Stone14"
	Stone15       = "T_Stone15"
	Stone16       = "T_Stone16"
	Stone17       = "T_Stone17"
	Stone18       = "T_Stone18"
	Stone19       = "T_Stone19"
	Stone20       = "T_Stone20"
	Stone21       = "T_Stone21"
	Stone22       = "T_Stone22"
	Stone23       = "T_Stone23"
	Stone24       = "T_Stone24"
	Stone25       = "T_Stone25"
	Stone26       = "T_Stone26"
	Stone27       = "T_Stone27"
	Stone28       = "T_Stone28"
	Stone29       = "T_Stone29"
	Stone30       = "T_Stone30"
	Stone31       = "T_Stone31"
	Stone32       = "T_Stone32"
	Stone33       = "T_Stone33"
	Stone34       = "T_Stone34"
	Stone35       = "T_Stone35"
	Stone36       = "T_Stone36"
	Stone37       = "T_Stone37"
	Stone38       = "T_Stone38"
	Stone39       = "T_Stone39"
	Stone40       = "T_Stone40"
	Stone41       = "T_Stone41"
	Stone42       = "T_Stone42"
	Stone43       = "T_Stone43"
	Stone44       = "T_Stone44"
)
